# Data config
DATA: str = (
    "/media/ssdraid/quentinmowat-amiet/Dropbox (IESE)/earnings_calls/Originals/Conference Calls/OLD/ccalls_from_stata.csv"  # CCALLS_copy.csv
)
DTYPE: dict = {
    "gvkey": "int",
    "new_text": "object",
}  # {'job': str, 'year': int, 'quarter': str, 'text': str, 'conm': str, 'gvkey': float}, was throwing error
JOB: str = "CEO"

# Model config
MODEL_FAMILY: str = "bge"
MODEL: str = f"{MODEL_FAMILY}-large-en-v1.5"
MODEL_PATH: str = f"BAAI/{MODEL}"

# Export config
# PROMPT: str = 'continuous'
EXPORT_TYPE: str = "ecalls"
EXPORT_FILE: str = f"{EXPORT_TYPE}_{MODEL_FAMILY}_{JOB}_test.csv"
EXPORT_PATH: str = (
    f"/media/ssdraid/quentinmowat-amiet/Dropbox (IESE)/earnings_calls/outputs/"
)
EXPORT_DATA: str = f"{EXPORT_PATH}{EXPORT_FILE}"

EXPORT_PNG: str = "histograms_of_scores0.png"
EXPORT_FIGURE: str = f"{EXPORT_PATH}{EXPORT_PNG}"

# Cultural/Structural attributes of interest
POSITIVE_ATTRIBUTES = [
    "centralized",
    "secretive",
    "hierarchical",
    "formal",
    "stagnating",
    "risk_averse",
]
NEGATIVE_ATTRIBUTES = [
    "decentralized",
    "transparent",
    "non_hierarchical",
    "informal",
    "innovative",
    "risk_taking",
]


CENTRALIZED_REVIEWS = [
    "Operates with a strict top-down approach, where decisions are made centrally. Team autonomy is limited, impacting creativity and innovation.",
    "Expect a structured environment with well-defined protocols. Roles are clear, but individual input and creativity are not encouraged.",
    "Employees work within a hierarchical system, where upper management makes key decisions without much input from lower levels.",
    "Decision-making is centralized for efficiency. The downside is limited empowerment for employees at lower levels, resulting in a lack of ownership.",
    "The organization follows a structured hierarchy, leading to clear roles but restricting flexibility. Decision-making predominantly happens at the top.",
    "Experience a workplace where departments operate independently with minimal collaboration, as decisions are made centrally.",
    "Top-down communication is emphasized, providing clear direction but limiting opportunities for employees to contribute ideas.",
    "Leadership is strong, and decisions are made centrally. However, there's limited room for lower-level employees to influence company-wide decisions.",
    "A well-defined structure ensures order, but it comes at the expense of limited involvement in decision-making for lower-level employees.",
    "Employees work within a structured environment, but there's limited participation in company-wide decisions for those at lower levels.",
    "Decision-making is centralized, leading to efficient processes but restricting autonomy for individual teams.",
    "Roles and responsibilities are clearly outlined, but there's limited influence on the overall company direction for individual employees.",
    "The company follows a top-down approach, resulting in efficient decision-making but limiting autonomy for employees.",
    "Expect clarity in roles and expectations, but there's limited input for employees in company-wide decisions.",
    "Operate within a structured environment with a clear chain of command, but there's limited room for individual initiative.",
    "Strong leadership is a highlight, but opportunities for employees to contribute to decision-making processes are limited.",
    "Centralized structure ensures consistency with clear guidelines, but there's limited space for creative problem-solving.",
    "Decisions are made efficiently within a centralized structure, but team autonomy is limited, following a top-down approach.",
    "A structured organization with defined roles is the norm. While expectations are clear, flexibility in decision-making is limited.",
    "Experience an efficient workplace where decisions are made centrally, but there's limited autonomy for teams and individuals.",
    "Concentrated",
    "Unified",
    "Consolidated",
    "Coordinated",
    "Integrated",
    "Commanded",
    "Directed",
    "Controlled",
    "Managed",
    "Regulated",
    "Organized",
    "Centralized",
    "Hierarchical",
    "Authoritarian",
    "Monolithic",
]


DECENTRALIZED_REVIEWS = [
    "Experience a decentralized work culture, where decision-making is distributed. Teams have the autonomy to be creative and innovative.",
    "Expect a dynamic environment with a focus on individual input and creativity. Roles are flexible, allowing for a variety of perspectives.",
    "Embrace a collaborative workplace where decisions are made at various levels. Lower-level employees have more influence on the direction.",
    "Enjoy a decentralized decision-making process that empowers employees at all levels. Ownership and accountability are encouraged.",
    "Operate within a flexible structure that encourages autonomy for individual teams. Decision-making is distributed throughout the organization.",
    "Experience a workplace where collaboration across teams is encouraged, and decisions are made collaboratively rather than from the top.",
    "Emphasizes bottom-up communication, providing opportunities for employees to contribute ideas. Decision-making is more inclusive.",
    "Leadership values input from all levels. Decision-making is distributed, allowing lower-level employees to influence company-wide decisions.",
    "A flexible structure ensures order with opportunities for lower-level employees to participate in decision-making processes.",
    "Employees work within a decentralized environment, with more participation in company-wide decisions for those at lower levels.",
    "Decision-making is distributed, promoting autonomy for individual teams. A collaborative approach ensures creativity and innovation.",
    "Roles and responsibilities are clear, but there's flexibility in individual input on the overall company direction.",
    "The company values a bottom-up approach, allowing for efficient decision-making while promoting autonomy for employees.",
    "Expect a workplace where input is encouraged, and there's more participation in company-wide decisions for employees at all levels.",
    "Operate within a dynamic organization that values individual initiative. Roles are defined, but flexibility in decision-making is encouraged.",
    "Leadership promotes a decentralized structure, ensuring opportunities for employees at all levels to contribute to decision-making processes.",
    "Decision-making is distributed to ensure diverse perspectives, with clear guidelines allowing for creative problem-solving.",
    "Decisions are made efficiently within a decentralized structure, allowing for team autonomy and a collaborative approach.",
    "Experience a workplace where roles are defined, but flexibility in decision-making is encouraged, following a bottom-up approach.",
    "A decentralized organization where decisions are made at various levels. Autonomy for teams and individuals is a key aspect.",
    "Distributed",
    "Dispersed",
    "Decentralized",
    "Fragmented",
    "Dissipated",
    "Scattered",
    "Disseminated",
    "Dispensed",
    "Unconsolidated",
    "Uncoordinated",
    "Autonomous",
    "Democratic",
    "Laissez-faire",
]


SECRETIVE_REVIEWS = [
    "Information about the company's operations is closely guarded, leaving both employees and external stakeholders in the dark.",
    "The company maintains a tight grip on information, leading to a lack of transparency in its dealings with both employees and external partners.",
    "Communication from the company is sparse and cryptic, creating an atmosphere of uncertainty for both insiders and outsiders.",
    "Both internal and external parties often find themselves grappling with a lack of information from the company, which seems intent on maintaining secrecy.",
    "The company's opaque communication style extends beyond its internal workings, affecting its interactions with clients and investors as well.",
    "Expect to encounter a company that operates behind closed doors, with limited insight into its operations provided to both internal and external stakeholders.",
    "Attempts to gather information about the company's activities are met with resistance, as it maintains a policy of secrecy with both employees and external parties.",
    "External stakeholders, like clients and investors, often lament the company's lack of transparency and tendency towards secrecy in its communications.",
    "The company's preference for secrecy extends to its interactions with external partners, making it difficult for stakeholders to gauge its intentions and strategies.",
    "Information shared by the company is often cryptic and selective, leaving both internal and external parties with only partial insights into its operations.",
    "The company's communication practices leave much to be desired, as it seems to prioritize secrecy in its dealings with both employees and external stakeholders.",
    "Expect to encounter a company that operates in the shadows, with little transparency provided to both internal and external parties about its decision-making processes and strategies.",
    "The company's reluctance to share information extends beyond its internal operations, creating challenges for external stakeholders seeking clarity and insight.",
    "Both employees and external partners often struggle to obtain clear, comprehensive information from the company, which seems to favor secrecy over openness.",
    "The company's communication style is characterized by ambiguity and discretion, leaving both insiders and outsiders with more questions than answers.",
    "The company's penchant for secrecy casts a shadow over its interactions with external stakeholders, who often find themselves excluded from key decision-making processes.",
    "Information provided by the company is often vague and elusive, contributing to a sense of opacity in its relationships with both employees and external parties.",
    "The company's lack of transparency extends beyond its internal operations, affecting its ability to foster trust and collaboration with external stakeholders as well.",
    "External stakeholders are often frustrated by the company's opaque communication style, which leaves them feeling uninformed and disconnected from its activities.",
    "The company's preference for secrecy creates barriers to collaboration with external partners, who struggle to obtain the information they need to engage effectively.",
    "Secretive",
    "Concealed",
    "Confidential",
    "Clandestine",
    "Covert",
    "Stealthy",
    "Underhanded",
    "Cloaked",
    "Hidden",
    "Opaque",
    "Cryptic",
    "Mysterious",
    "Reserved",
    "Evasive",
]


TRANSPARENT_REVIEWS = [
    "The company fosters an environment of openness and clarity, where information flows freely among employees, promoting collaboration and trust.",
    "Communication within the company is refreshingly clear and unambiguous, empowering employees at all levels to make informed decisions.",
    "Expect to encounter a company that values transparency, with open communication channels that facilitate collaboration and innovation.",
    "The company's commitment to clarity and openness extends to its interactions with external stakeholders, fostering strong relationships built on trust.",
    "Information within the company is readily accessible and transparent, enabling employees to understand the bigger picture and contribute meaningfully to the organization's goals.",
    "The company operates with a policy of transparency, providing employees with clear insights into decision-making processes and strategic direction.",
    "Both internal and external stakeholders benefit from the company's transparent communication practices, which promote accountability and foster trust.",
    "Transparency is the cornerstone of the company's communication strategy, ensuring that employees and external partners are kept informed and engaged.",
    "Employees appreciate the company's commitment to openness and honesty, which creates a culture of trust and mutual respect.",
    "The company's transparent communication style sets it apart, fostering a sense of inclusivity and empowerment among employees and external stakeholders alike.",
    "Expect to encounter a company where information is shared openly and transparently, empowering employees to take ownership of their roles and contribute to the organization's success.",
    "The company's transparent approach to communication instills confidence in both employees and external partners, fostering strong, collaborative relationships.",
    "Transparency is not just a buzzword at this company; it's a guiding principle that shapes every aspect of its operations and interactions with stakeholders.",
    "The company's commitment to transparency creates a culture of accountability, where decisions are made openly and with the best interests of all stakeholders in mind.",
    "Employees value the company's transparent communication practices, which provide clarity and foster a sense of belonging and purpose.",
    "Transparency is woven into the fabric of the company's culture, creating an environment where trust and collaboration thrive.",
    "The company's transparent communication style builds credibility with both employees and external partners, strengthening its reputation as a trustworthy and reliable organization.",
    "Expect to find a company that values openness and transparency in its interactions with all stakeholders, promoting a culture of trust and cooperation.",
    "Transparency is a core value of the company, reflected in its commitment to providing clear, honest communication to both internal and external audiences.",
    "The company's transparent communication practices create an atmosphere of trust and accountability, where everyone feels valued and informed.",
    "Transparent",
    "Clear",
    "Visible",
    "Open",
    "Evident",
    "Obvious",
    "Apparent",
    "Lucid",
    "Plain",
    "Unambiguous",
    "Straightforward",
    "Honest",
    "Candid",
    "Direct",
    "Explicit",
    "Intelligible",
]


HIERARCHICAL_REVIEWS = [
    "The company operates with a clear chain of command, where decisions trickle down from executives to managers and finally to employees.",
    "Expect to encounter a hierarchical organization where authority and decision-making power are concentrated at the top, with limited autonomy for lower-level employees.",
    "The company's hierarchical structure fosters clear roles and responsibilities, but can sometimes stifle innovation and creativity among lower-level employees.",
    "Employees navigate a hierarchical system where communication flows predominantly from top to bottom, with little opportunity for upward feedback or input.",
    "The company's hierarchical organization ensures clear lines of authority, but can sometimes lead to bureaucratic inefficiencies and slow decision-making processes.",
    "Managers play a central role in the company's hierarchical structure, serving as intermediaries between executives and frontline employees.",
    "Expect to encounter a company where power and authority are centralized among executives and senior managers, creating a hierarchical culture that can be difficult to navigate.",
    "The company's hierarchical structure provides employees with clear reporting relationships, but can sometimes result in a lack of autonomy and empowerment.",
    "Communication within the company follows a hierarchical pattern, with directives flowing from upper management to middle managers and eventually to frontline employees.",
    "The hierarchical nature of the company's organization can sometimes lead to a disconnect between executives, managers, and employees, hindering collaboration and innovation.",
    "Employees operate within a clearly defined hierarchical system, where decision-making authority is concentrated at the top and gradually diminishes as it cascades down.",
    "The company's hierarchical structure promotes efficiency and order, but can sometimes create barriers to communication and collaboration between different levels of the organization.",
    "Expect to find a company where hierarchical relationships dictate the flow of information and decision-making processes, with executives wielding the most power and influence.",
    "Managers are tasked with implementing the directives handed down from executives, reinforcing the hierarchical structure of the company's organization.",
    "The hierarchical organization of the company can sometimes result in a lack of flexibility and adaptability, as decisions must navigate through multiple layers of management.",
    "Employees at lower levels of the company's hierarchy may feel disconnected from decision-making processes, as authority and influence are concentrated at the top.",
    "The hierarchical nature of the company's organization can sometimes create silos between departments, hindering collaboration and knowledge sharing.",
    "Expect to encounter a company where executives hold the reins of power, delegating authority to managers who oversee the day-to-day operations and employees who execute tasks.",
    "Communication within the company follows a strict hierarchical structure, with information flowing downward from executives to managers and eventually to employees.",
    "The company's hierarchical organization provides clear reporting relationships and accountability, but can sometimes lead to a lack of innovation and agility.",
    "Hierarchical",
    "Pyramidal",
    "Tiered",
    "Graded",
    "Stratified",
    "Ranked",
    "Structured",
    "Ordered",
    "Layered",
    "Cascade",
    "Top-down",
    "Dominant-subordinate",
    "Vertical",
]


NON_HIERARCHICAL_REVIEWS = [
    "The company embraces a flat organizational structure, where decision-making power is decentralized and employees are empowered to take ownership of their work.",
    "Expect to encounter a company where authority is distributed evenly among employees, fostering a collaborative and inclusive work environment.",
    "The company's non-hierarchical structure promotes open communication and teamwork, with employees encouraged to contribute ideas and take on leadership roles.",
    "Managers at the company serve as facilitators rather than gatekeepers, empowering employees to make autonomous decisions and drive projects forward.",
    "Communication within the company flows freely across all levels, with employees encouraged to share feedback and ideas regardless of their position in the hierarchy.",
    "The company operates with a flat management structure, where employees have direct access to executives and decision-making processes are transparent and inclusive.",
    "Expect to encounter a company where titles and ranks matter less than contributions and collaboration, fostering a culture of mutual respect and cooperation.",
    "Managers at the company act as mentors and coaches, supporting employees in their professional development rather than dictating tasks and directives.",
    "The company's non-hierarchical organization promotes a sense of ownership and accountability among employees, driving innovation and creativity.",
    "Employees at the company enjoy a high degree of autonomy and flexibility in their work, with decision-making authority distributed across all levels of the organization.",
    "The company's flat organizational structure promotes agility and responsiveness, allowing it to adapt quickly to changing market conditions and customer needs.",
    "Expect to find a company where hierarchy takes a backseat to collaboration and teamwork, with employees empowered to make decisions and drive initiatives forward.",
    "The company's non-hierarchical approach to management fosters a culture of trust and empowerment, where employees feel valued and supported in their roles.",
    "Managers at the company focus on removing barriers and facilitating communication, rather than micromanaging employees or imposing top-down directives.",
    "The company's non-hierarchical structure encourages employees to take initiative and pursue their passions, leading to greater job satisfaction and engagement.",
    "Expect to encounter a company where everyone's voice is heard and respected, regardless of their title or position in the organization's hierarchy.",
    "The company's flat organizational structure promotes transparency and accountability, with decision-making processes accessible to all employees.",
    "Managers at the company serve as advocates for their teams, providing support and guidance rather than wielding authority or control.",
    "The company's non-hierarchical culture promotes collaboration and innovation, with employees empowered to experiment and take risks in pursuit of excellence.",
    "Expect to find a company where leadership is distributed among all employees, fostering a sense of ownership and responsibility for the company's success.",
    "Non-hierarchical",
    "Flat",
    "Horizontal",
    "Non-structured",
    "Unstructured",
    "Equal",
    "Peer-to-peer",
    "Collaborative",
    "Team-based",
    "Lateral",
    "Cooperative",
    "Non-rank",
    "Communal",
]


FORMAL_REVIEWS = [
    "The company operates with a high degree of formalization, where rules and procedures govern every aspect of its operations, ensuring consistency and adherence to standards.",
    "Expect to encounter a company where processes are well-defined and strictly adhered to, creating a structured and orderly work environment.",
    "The company's formalized approach to management ensures that decisions are made based on established rules and procedures, minimizing ambiguity and promoting accountability.",
    "Managers at the company rely on formal protocols and guidelines to guide their decision-making processes, ensuring consistency and fairness.",
    "Communication within the company follows formal channels and protocols, with information documented and disseminated according to established procedures.",
    "Expect to find a company where adherence to rules and procedures is paramount, creating a culture of discipline and accountability.",
    "The company's formalized structure promotes efficiency and order, with clear roles and responsibilities outlined for every employee.",
    "Managers at the company enforce formal policies and procedures to maintain consistency and ensure compliance with regulatory requirements.",
    "Expect to encounter a company where documentation and record-keeping are taken seriously, with formalized processes in place to track and monitor activities.",
    "The company's formal approach to management fosters a sense of professionalism and discipline among employees, driving high performance and accountability.",
    "Managers at the company are responsible for upholding formal standards and protocols, ensuring that employees adhere to established guidelines and procedures.",
    "Expect to find a company where decision-making is based on data and evidence, with formalized processes in place to assess risks and evaluate opportunities.",
    "The company's formalized structure provides employees with clear guidelines and expectations, minimizing confusion and promoting consistency.",
    "Managers at the company are trained to follow formal procedures and protocols when handling issues and making decisions, ensuring fairness and impartiality.",
    "Expect to encounter a company where compliance with rules and regulations is non-negotiable, with formalized processes in place to monitor and enforce adherence.",
    "The company's formal approach to management ensures that decisions are made transparently and objectively, with documentation to support the rationale behind each action.",
    "Managers at the company rely on formalized performance metrics and benchmarks to evaluate employee performance and track progress towards goals.",
    "Expect to find a company where procedures and protocols are rigorously enforced, creating a culture of accountability and continuous improvement.",
    "The company's formalized structure promotes consistency and predictability, with clear expectations set for performance and behavior.",
    "Managers at the company are responsible for ensuring that employees understand and comply with formal policies and procedures, promoting a culture of compliance and accountability.",
    "Formal",
    "Standardized",
    "Regulated",
    "Structured",
    "Rigid",
    "Systematized",
    "Official",
    "Procedural",
    "Conventional",
    "Bureaucratic",
    "Rule-bound",
    "Protocol-driven",
    "Methodical",
    "Traditional",
    "Compliant",
]


INFORMAL_REVIEWS = [
    "The company operates with a high degree of informality, where rules and procedures are flexible and employees are encouraged to take initiative and innovate.",
    "Expect to encounter a company where processes are fluid and adaptable, allowing for creativity and experimentation.",
    "The company's informal approach to management fosters a culture of collaboration and creativity, where employees are empowered to think outside the box and take risks.",
    "Managers at the company embrace informality, encouraging open communication and flexibility in decision-making processes.",
    "Communication within the company is informal and spontaneous, with employees encouraged to share ideas and feedback in a relaxed atmosphere.",
    "Expect to find a company where hierarchy takes a backseat to collaboration and teamwork, fostering a culture of openness and inclusivity.",
    "The company's informal structure promotes agility and innovation, allowing it to quickly adapt to changing market conditions and customer needs.",
    "Managers at the company prioritize trust and empowerment over strict adherence to rules and procedures, allowing employees the freedom to explore new ideas and approaches.",
    "Expect to encounter a company where creativity is valued and celebrated, with employees given the freedom to experiment and learn from failure.",
    "The company's informal approach to management fosters a sense of camaraderie and trust among employees, leading to greater job satisfaction and engagement.",
    "Managers at the company serve as mentors and coaches, providing support and guidance in an informal and approachable manner.",
    "Expect to find a company where decision-making is decentralized and collaborative, with employees at all levels empowered to contribute to the decision-making process.",
    "The company's informal culture promotes transparency and openness, with communication channels kept informal and accessible to all employees.",
    "Managers at the company lead by example, fostering an informal work environment where employees feel comfortable sharing their ideas and concerns.",
    "Expect to encounter a company where the emphasis is on results rather than rigid adherence to rules and procedures, allowing for flexibility and creativity in problem-solving.",
    "The company's informal structure promotes a culture of trust and autonomy, where employees are given the freedom to manage their own workload and make decisions.",
    "Managers at the company prioritize building relationships and fostering collaboration, creating an informal and supportive work environment.",
    "Expect to find a company where innovation is encouraged and rewarded, with employees given the freedom to pursue their ideas and take risks.",
    "The company's informal approach to management fosters a culture of continuous learning and improvement, with employees encouraged to share knowledge and best practices.",
    "Managers at the company focus on building strong teams and fostering a sense of belonging, creating an informal and inclusive work environment.",
    "Informal",
    "Casual",
    "Relaxed",
    "Unstructured",
    "Flexible",
    "Laid-back",
    "Non-formal",
    "Easygoing",
    "Loose",
    "Unconventional",
    "Open",
    "Flexible",
    "Adaptable",
    "Spontaneous",
    "Free-flowing",
    "Non-restrictive",
]


STAGNATING_REVIEWS = [
    "The company operates in a stagnant industry, with traditional business practices and a slow-moving approach to innovation.",
    "Expect to encounter a company that is a laggard in its industry, with little investment in research and development and a reluctance to embrace new technologies.",
    "The company's traditional mindset and slow-moving approach to change have left it trailing behind competitors in terms of innovation and growth.",
    "Managers at the company are resistant to change and innovation, preferring to stick to traditional methods and avoid taking risks.",
    "Expect to find a company that is slow to adapt to market trends and technological advancements, with a culture that stifles innovation and creativity.",
    "The company's lack of investment in research and development has resulted in a stagnating product lineup and a loss of market share to more innovative competitors.",
    "Managers at the company prioritize maintaining the status quo over driving innovation, resulting in a stagnant culture that lacks energy and excitement.",
    "Expect to encounter a company that is resistant to change and innovation, with a culture that values tradition and stability over growth and progress.",
    "The company's slow-moving approach to decision-making and risk aversion have hindered its ability to innovate and respond quickly to market changes.",
    "Managers at the company are hesitant to invest in new ideas and technologies, leading to a stagnant culture that is resistant to change.",
    "Expect to find a company that is stuck in the past, with outdated processes and a lack of investment in modernization and innovation.",
    "The company's low investment in research and development has left it trailing behind competitors in terms of product innovation and customer satisfaction.",
    "Managers at the company are focused on maintaining the status quo rather than driving growth and innovation, leading to a culture of complacency and stagnation.",
    "Expect to encounter a company where innovation is viewed as a risk rather than an opportunity, with little appetite for change and experimentation.",
    "The company's conservative approach to business has resulted in a stagnating product portfolio and a decline in market competitiveness.",
    "Managers at the company are resistant to new ideas and technologies, preferring to stick with what has worked in the past rather than embracing change.",
    "Expect to find a company that is slow to adapt to changing market dynamics and customer needs, with a culture that is resistant to innovation and progress.",
    "The company's lack of investment in research and development has led to a stagnating culture that is unable to keep pace with the rapidly evolving business landscape.",
    "Managers at the company are focused on maintaining existing processes and systems rather than driving innovation and improvement, leading to a culture of stagnation.",
    "Expect to encounter a company that is slow to respond to market changes and technological advancements, with a culture that is resistant to change and innovation.",
    "Stagnating",
    "Laggard",
    "Outdated",
    "Obsolete",
    "Backward",
    "Outmoded",
    "Archaic",
    "Antiquated",
    "Out-of-date",
    "Dated",
    "Old-fashioned",
    "Retrograde",
    "Stale",
    "Regressive",
]


INNOVATIVE_REVIEWS = [
    "The company prides itself on its innovative culture, where employees are encouraged to think outside the box and pursue new ideas.",
    "Expect to encounter a company that is at the forefront of innovation, with a track record of introducing groundbreaking products and services to the market.",
    "The company's forward-thinking approach to business has earned it a reputation as an industry leader in innovation and technology.",
    "Managers at the company foster a culture of innovation and experimentation, empowering employees to take risks and explore new opportunities.",
    "Expect to find a company that invests heavily in research and development, fueling its reputation as a hub of innovation and creativity.",
    "The company's commitment to innovation sets it apart from competitors, with a focus on developing cutting-edge solutions to meet customer needs.",
    "Managers at the company prioritize innovation and creativity in their teams, recognizing that breakthrough ideas are essential for long-term success.",
    "Expect to encounter a company that embraces change and disruption, with a culture that encourages agility and adaptability in the face of evolving market dynamics.",
    "The company's investment in research and development has led to a pipeline of innovative products and services that drive growth and profitability.",
    "Managers at the company are champions of innovation, creating an environment where employees are empowered to challenge the status quo and pioneer new solutions.",
    "Expect to find a company that thrives on innovation, with a commitment to fostering a culture of curiosity, experimentation, and continuous improvement.",
    "The company's focus on innovation extends beyond product development to all areas of the business, driving efficiency, effectiveness, and customer satisfaction.",
    "Managers at the company encourage collaboration and cross-functional teamwork, recognizing that diverse perspectives are essential for driving innovation and creativity.",
    "Expect to encounter a company that values creativity and problem-solving skills, with a culture that rewards bold ideas and entrepreneurial spirit.",
    "The company's commitment to innovation is evident in its investment in cutting-edge technologies and its willingness to explore new markets and business models.",
    "Managers at the company lead by example, demonstrating a willingness to take risks and embrace uncertainty in pursuit of innovation and growth.",
    "Expect to find a company that fosters a culture of continuous learning and improvement, with programs and initiatives in place to support employee development and innovation.",
    "The company's culture of innovation is supported by a robust infrastructure for idea generation, testing, and implementation, ensuring that innovative ideas are brought to market quickly and efficiently.",
    "Managers at the company are proactive in seeking out new opportunities for growth and innovation, leveraging their networks and resources to stay ahead of the curve.",
    "Expect to encounter a company that values diversity and inclusion, recognizing that different perspectives and experiences are essential for driving innovation and creativity.",
    "Innovative",
    "Pioneering",
    "Cutting-edge",
    "Groundbreaking",
    "Revolutionary",
    "Trailblazing",
    "Forward-thinking",
    "Visionary",
    "Progressive",
    "Creative",
    "Original",
    "Inventive",
    "Disruptive",
    "Avant-garde",
    "Leading-edge",
]


RISK_AVERSE_REVIEWS = [
    "The company operates in a risk-averse industry, with a conservative approach to decision-making and a reluctance to embrace change.",
    "Expect to encounter a company that prioritizes stability and predictability over innovation and growth, with a culture that is resistant to taking risks.",
    "The company's risk-averse mindset has led to a culture of complacency and stagnation, with little appetite for experimentation or disruption.",
    "Managers at the company are hesitant to take risks or deviate from established processes, preferring to stick with what has worked in the past rather than embrace change.",
    "Expect to find a company that is slow to adapt to market changes and technological advancements, with a culture that is resistant to taking risks or exploring new opportunities.",
    "The company's risk-averse culture stifles creativity and innovation, with employees discouraged from challenging the status quo or proposing new ideas.",
    "Managers at the company prioritize avoiding failure over pursuing growth and innovation, leading to a culture of risk aversion and inertia.",
    "Expect to encounter a company where decision-making is driven by fear of failure rather than a desire for success, with little tolerance for uncertainty or ambiguity.",
    "The company's risk-averse approach to business has resulted in missed opportunities and lost market share, as competitors with a higher tolerance for risk have outpaced its growth.",
    "Managers at the company are resistant to change and reluctant to take risks, preferring to maintain the status quo rather than explore new opportunities or strategies.",
    "Expect to find a company that is reactive rather than proactive, with a culture that is focused on avoiding mistakes rather than seizing opportunities.",
    "The company's risk-averse culture breeds a fear of failure among employees, inhibiting creativity and innovation and stifling growth and progress.",
    "Managers at the company are quick to shoot down new ideas or proposals that deviate from established norms or processes, reinforcing a culture of risk aversion and conformity.",
    "Expect to encounter a company where decision-making is centralized and conservative, with little room for experimentation or deviation from the established playbook.",
    "The company's risk-averse mindset is reflected in its decision-making processes, which prioritize minimizing potential losses over maximizing potential gains.",
    "Managers at the company are focused on preserving the status quo rather than driving change or innovation, leading to a culture of risk aversion and resistance to new ideas.",
    "Expect to find a company that is slow to adapt to emerging trends and market opportunities, with a culture that is hesitant to take risks or explore uncharted territory.",
    "The company's risk-averse culture stifles employee creativity and initiative, with little room for experimentation or exploration of new ideas.",
    "Managers at the company are quick to reject proposals that involve significant risk or uncertainty, preferring to stick with what is known and familiar rather than venture into the unknown.",
    "Expect to encounter a company where decision-making is driven by consensus and caution, with little tolerance for ambiguity or uncertainty.",
    "Risk-averse",
    "Skeptical",
    "Cautious",
    "Conservative",
    "Wary",
    "Prudent",
    "Reserved",
    "Reluctant",
    "Hesitant",
    "Apprehensive",
    "Careful",
    "Concerned",
    "Inhibited",
    "Doubtful",
    "Tentative",
]


RISK_TAKING_REVIEWS = [
    "The company prides itself on its risk-taking culture, where employees are encouraged to take bold initiatives and explore new opportunities.",
    "Expect to encounter a company that is known for its willingness to take risks and pursue ambitious goals, with a culture that rewards innovation and entrepreneurship.",
    "The company's risk-taking mindset has propelled it to the forefront of its industry, with a track record of pioneering new technologies and business models.",
    "Managers at the company are empowered to take calculated risks and experiment with new ideas, fostering a culture of creativity and innovation.",
    "Expect to find a company that embraces change and disruption, with a culture that encourages agility and adaptability in the face of uncertainty.",
    "The company's willingness to take risks and challenge the status quo has enabled it to stay ahead of competitors and drive growth and profitability.",
    "Managers at the company lead by example, demonstrating a willingness to take calculated risks and push the boundaries of what is possible.",
    "Expect to encounter a company where decision-making is decentralized and entrepreneurial, with employees at all levels empowered to take ownership of their ideas and initiatives.",
    "The company's risk-taking culture fosters a spirit of creativity and innovation, with employees encouraged to explore new ideas and experiment with new approaches.",
    "Managers at the company are encouraged to think outside the box and take calculated risks in pursuit of ambitious goals and objectives.",
    "Expect to find a company that values boldness and initiative, with a culture that rewards employees who are willing to take risks and challenge the status quo.",
    "The company's willingness to take risks and invest in new opportunities has positioned it as a leader in its industry, with a reputation for innovation and forward-thinking.",
    "Managers at the company are given the freedom to pursue unconventional ideas and strategies, with a culture that celebrates creativity and risk-taking.",
    "Expect to encounter a company where failure is viewed as a learning opportunity rather than a setback, with a culture that encourages experimentation and resilience.",
    "The company's risk-taking culture is supported by a robust infrastructure for idea generation, testing, and implementation, ensuring that innovative ideas are brought to market quickly and efficiently.",
    "Managers at the company are encouraged to challenge assumptions and explore new possibilities, fostering a culture of curiosity and exploration.",
    "Expect to find a company that is not afraid to disrupt itself, with a culture that values agility and adaptability in the face of changing market dynamics.",
    "The company's willingness to take risks and embrace uncertainty has fueled its growth and success, with a culture that celebrates boldness and resilience.",
    "Managers at the company are given the autonomy to experiment with new ideas and approaches, with a culture that values creativity and innovation over conformity and predictability.",
    "Expect to encounter a company where risk-taking is not only encouraged but celebrated, with a culture that rewards employees who are willing to push the boundaries and challenge the status quo.",
    "Risk-taking",
    "Daring",
    "Bold",
    "Adventurous",
    "Courageous",
    "Venturesome",
    "Audacious",
    "Gutsy",
    "Venturous",
    "Enterprising",
    "Risk-seeking",
    "Speculative",
    "Exploratory",
]


CENTRALIZED_EARNINGS_CALLS = [
    "Our decision-making is centralized to ensure strategic alignment. This approach enhances efficiency and consistency across all departments.",
    "We follow a centralized structure to streamline operations. This allows us to make agile decisions and maintain a clear focus on our objectives.",
    "Centralizing decision-making is a key aspect of our corporate strategy. It promotes a cohesive vision and ensures rapid execution of our initiatives.",
    "The centralized nature of our organization fosters a strong leadership framework. This ensures that key decisions are made with a unified vision.",
    "We've adopted a centralized model to facilitate quick responses to market changes. This approach enables us to navigate challenges with agility.",
    "Our commitment to a centralized structure is driven by the need for a synchronized approach. It enhances coordination and resource allocation efficiency.",
    "Centralized decision-making has proven instrumental in maintaining a cohesive company culture. It helps align our teams with our overarching goals.",
    "We emphasize a centralized approach to decision-making to enhance accountability. This ensures that responsibility is clearly defined across the organization.",
    "Our centralized structure promotes a top-down communication flow. This facilitates effective dissemination of information and swift decision implementation.",
    "Centralization is a cornerstone of our operational strategy. It allows us to adapt swiftly to market dynamics and execute on our long-term vision.",
    "Our decision-making is intentionally centralized to foster uniformity in our actions. This ensures that our strategic goals are the driving force behind every decision.",
    "The centralized nature of our organization enables us to respond decisively to industry trends. It ensures that our actions are coherent and impactful.",
    "We've strategically maintained a centralized structure to uphold a unified corporate identity. This allows us to present a cohesive front to our stakeholders.",
    "Centralized decision-making is pivotal for maintaining a consistent customer experience. It ensures that our services align seamlessly with our brand values.",
    "Our commitment to a centralized structure enhances our risk management capabilities. It allows for a comprehensive assessment of potential challenges.",
    "The benefits of a centralized approach are evident in our streamlined processes. This ensures that our resources are optimized for maximum efficiency.",
    "Centralization plays a crucial role in our strategic planning. It allows us to act swiftly on opportunities and ensures alignment with our corporate vision.",
    "Our emphasis on a centralized structure is designed to enhance operational efficiency. It enables us to navigate complexities with a unified strategy.",
    "Centralized decision-making is fundamental to our adaptability. It ensures that we can pivot swiftly in response to market demands and opportunities.",
    "The centralized nature of our organization is key to fostering a sense of unity among our teams. It strengthens collaboration and collective problem-solving.",
    "Our commitment to centralization is a testament to our dedication to strategic coherence. It enables us to navigate the business landscape with a clear and focused approach.",
]


DECENTRALIZED_EARNINGS_CALLS = [
    "Decentralization is a key aspect of our company culture. It empowers teams to make decisions autonomously, fostering innovation and agility.",
    "We've embraced a decentralized model to encourage creativity and diversity in decision-making. This approach allows for more dynamic responses to market changes.",
    "Our commitment to decentralization is rooted in fostering a culture of individual initiative. It empowers employees at all levels to contribute to our success.",
    "Decentralized decision-making is pivotal for us to stay nimble in a rapidly evolving industry. It allows us to harness the diverse expertise within our teams.",
    "We intentionally follow a decentralized approach to empower our teams with the flexibility to respond to local market nuances. This ensures a tailored strategy.",
    "Decentralization is ingrained in our organizational DNA. It promotes a bottom-up flow of ideas, encouraging employees to contribute to our collective success.",
    "Our decentralized structure is designed to facilitate a more inclusive decision-making process. It empowers employees to actively shape our company's direction.",
    "We believe in the strength of decentralized decision-making to foster a culture of ownership. It allows us to leverage the expertise and insights of our teams.",
    "Decentralization is a driving force behind our adaptability. It ensures that decision-making is distributed, enabling us to swiftly respond to market dynamics.",
    "We've strategically adopted a decentralized model to promote flexibility and innovation. This approach encourages experimentation and continuous improvement.",
    "Decentralization is core to our philosophy of empowering employees. It ensures that decision-making is not limited to the top, fostering a collaborative culture.",
    "Our commitment to decentralization is rooted in the belief that diverse perspectives drive innovation. It allows us to harness the collective intelligence of our teams.",
    "Decentralized decision-making is fundamental to our responsiveness. It empowers teams to act swiftly and make decisions aligned with their unique insights.",
    "We've embraced decentralization to tap into the collective intelligence of our workforce. This ensures that decision-making is informed by diverse perspectives.",
    "Our decentralized structure promotes individual accountability and ownership. It allows us to respond to market changes with speed and adaptability.",
    "Decentralization is key to our ability to navigate regional complexities. It ensures that decision-making is responsive to the unique challenges and opportunities in each market.",
    "We intentionally foster a decentralized culture to empower employees to take ownership of their work. It leads to more engaged and motivated teams.",
    "Our commitment to decentralization is driven by the belief that innovation thrives in an environment where decision-making is distributed. It's the foundation of our success.",
    "Decentralized decision-making is a strategic advantage for us. It ensures that decision authority is distributed, enabling us to tap into the expertise of all teams.",
    "We believe in decentralization as a catalyst for innovation. It allows us to tap into the collective intelligence of our teams, driving continuous improvement.",
]
